version: '3.1'

services:
  db:
    image: postgres
    restart: always
    # TODO put this to an env file
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
